### ISSUE TITLE
Upgrade Notifications Email to dotnet v9

### ISSUE THREAD

**Issue by hggutvik** [Altinn/altinn-notifications-email#110]
### Description

We should upgrade the Notifications Email application to .net9. .net9 has standard time support until May 12, 2026, but we should take the time to upgrade and not wait for .net 10. 

### Additional Information

[.NET Core Support lifecycle](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)
[Container Patching](https://pedia.altinn.cloud/altinn-3/ops/patching/containers/#net-core)

### Tasks

- [x] Update base images in the dockerfile for .net9
- [x] Bump all projects; src and test, to .net9
- [ ] Update any build pipelines to support .net9
- [x] Update any github workflows with .net9
- [x] Check if we need to change anything in SonarCloud

### Acceptance Criterias

- [x] Notifications Email is built with .net9 tooling and run on .net9 Description

**Comment by Ahmed-Ghanam** [comment]
The release pipelines for this application depend on agents from the "altinn-vmss-platformagent" pool. To ensure seamless releases and maintain compatibility, it is crucial to install .NET Framework version 9.0 on all agents within this pool. [The Platform team will handle the installation of .NET Framework version 9.0 across all agents](https://github.com/Altinn/altinn-platform/issues/1207). We will not be able to publish the changes until the Platform team has completed the update of the agents.
